server:
  port: 8899
spring:
  profiles:
    active: test
  datasource: #数据源相关的配置节点
    type: com.zaxxer.hikari.HikariDataSource   #
    driver-class-name: com.mysql.cj.jdbc.Driver   #
    url: jdbc:mysql://localhost:3306/imooc-springboot-learn?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: password #root
    hikari:
      connection-timeout: 30000     #等待连接池分配连接的最大市场（毫秒），超过这个时长还没有可用的连接则发生SQLException,默认30秒
      minimum-idle: 5               #最小链接数
      maximum-pool-size: 20         #最大连接数
      auto-commit: true             #自动提交
      idle-timeout: 600000          #连接超时的最大时长（毫秒），超时这被释放（retired）默认：10分钟
      pool-name: DateSourceHikariCP #连接池名字
      max-lifetime: 180000          #连接池的生成时长（毫秒），超时而且没被使用则被释放（retired）默认：30分钟
      connection-test-query: SELECT 1
logging:
  servlet:
    multipart:
      max-file-size: 500KB #文件上传大小的限制，设置最大值，不能超过，否在报错
      max-request-size: 2MB #文件最大请求限制，用于批量
  banner:
    location: classpath:banner/banner.txt
  level:
    root: warn
    com.cscec3b.mapper: trace
  pattern:
    console: '%p%m%n'
mybatis-plus:
  mapper-locations: ["classpath*:/mapper/**/*.xml"]
#  mapper-locations: classpath:mapper/*
  global-config:
    db-config:
      id-type: ASSIGN_ID #全局id生成策略
#  config-location: classpath:mybatis-config.xml